spring:
  application:
    name: ms-clien
  datasource:
    url: jdbc:h2:mem:clients_db
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    
server:
  port: 9094
  