spring:
  application:
    name: ms-financial-product
  datasource:
    url: jdbc:h2:mem:financial-product_db
    username: sa
    password:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console


server:
  port: 9093
